Dota2_trader/Dota2_trader/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dota2_deco/',include('dota2_deco.urls')),
    path('login/',include('login_app.urls')),
]

Dota2_trader/dota2_deco/urls.py
from django.urls import path
 
from . import views
app_name = 'dota2_deco'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('search/',views.search, name='search'),
    path('publish/',views.publish, name='publish'),
    path('publish/item_upload/',views.item_upload, name='item_upload'),
]

Dota2_trader/login_app/urls.py
from django.urls import path
 
from . import views

app_name = 'login_app'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('forget_password', views.forget_password, name='forget_password'),
    path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
]

Dota2_trader/dota2_deco/models.py
import datetime
from django.db import models

from django.utils import timezone

# # Create your models here.
class Decorations(models.Model):
    
    decoration_name = models.CharField(max_length=200)
    decoration_champion = models.CharField(max_length=50)
    decoration_part = models.CharField(max_length=50)
    decoration_rarelity = models.CharField(max_length=50)
    decoration_average_price = models.FloatField()

    def __str__(self):
        return self.decoration_name

    def recent_average_price(self):
        return self.decoration_average_price

class Items(models.Model):
    
    item_id = models.AutoField(primary_key=True)
    item_type = models.ForeignKey(Decorations, on_delete=models.CASCADE)
    publisher_id = models.CharField(max_length=50)
    price = models.FloatField()
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return f" {self.item_type} ${self.price} by {self.publisher_id}"

Dota2_trader/login_app/models.py
from django.db import models

# Create your models here.dd
class User(models.Model):
	"""docstring for user"""
	user_name = models.CharField(max_length=200)
	user_email = models.CharField(max_length=200)
	user_password = models.CharField(max_length=200)

	def __str__(self):
		return f"{self.user_name} {self.email}"

Dota2_trader/login_app/forms.py
from django import forms
 
class password_reset(forms.Form):
   Email = forms.EmailField()
   def __str__(self):
       return self.Email

Dota2_trader/dota2_deco/views.py
from django.shortcuts import render, get_object_or_404
import random
import datetime
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Decorations, Items

#edit if fulltext search
def index(request):
    latest_item_list = Items.objects.order_by('-pub_date')
    template = loader.get_template('dota2_deco/index.html')
    context = {
        'latest_item_list': latest_item_list[:20],
    }
    return HttpResponse(template.render(context, request))

def detail(request, item_id):
    item = get_object_or_404(Items, pk=item_id)
    return render(request, 'dota2_deco/detail.html', {'item': item, 'decoration': item.item_type})

#edit if keyword search
@csrf_exempt
def search(request):
    keyword = request.POST.get('keyword')

    # cheapest_item_list = Items.objects.filter(item_type=keyword).order_by('price')
    all_results = Items.objects.all()
    lastest_results = all_results.order_by('pub_date')

    # filter by item_type == keyword
    result = []
    for each in all_results.order_by('price'):
        if each.item_type.decoration_name == keyword:
            result.append(each)

    context = {
        'user_search_results': result[:20],
        'latest_item_list': lastest_results[:10],
        'keyword': keyword
    }
    return render(request,'dota2_deco/index.html',context)

#publishing item
def publish(request):
    type_list = Decorations.objects.all()
    context = {
        'type_list':type_list,
    }
    return render(request,'dota2_deco/publish.html',context)

#upload item to the database
@csrf_exempt
def item_upload(request):
    this_type = request.POST['type']
    this_price = request.POST['price']
    this_publisher = 'default_user'
    this_decoration = Decorations.objects.get(decoration_name=this_type)
    this_item = Items(item_type=this_decoration,publisher_id=this_publisher,price=float(this_price),pub_date=datetime.datetime.now())
    this_item.save()

    all_results = Items.objects.all()
    # filter by item_type == this_type
    result = []
    for each in all_results:
        if each.item_type.decoration_name == this_type:
            result.append(each)
    total_price = 0
    count=0
    for each_item in result:
        total_price += each_item.price
        count +=1

    this_decoration.decoration_average_price = total_price/count
    this_decoration.save()

    return render(request,'dota2_deco/publish_success.html')

Dota2_trader/login_app/views.py
from django.shortcuts import render
from Dota2_trader.settings import EMAIL_HOST_USER
from . import forms
from django.core.mail import send_mail
from .models import User
# Create your views here.

def index(request):
    return render(request,'login_page.html')
    # return HttpResponse("hello")

def forget_password(request):
    return render(request,'forget_password/forget_password.html')

def password_reset_request(request):
    if request.method == 'POST':
        subject = 'password reset'
        message = 'localhost:8000/'
        recepient = str(sub['Email'].value())
        if not User.objects.filter(user_email=recepient).exists():
            return render(request, 'forget_password/failed.html', {'recepient': recepient})
        else:
            send_mail(subject,
                message, EMAIL_HOST_USER, [recepient], fail_silently=False)
            return render(request, 'forget_password/successed.html', {'form': sub})

def password_reset(request):
    if request.method == 'POST':
        account = User.objects.get(email=request.POST[email])
        return render(request, 'forget_password/reset_successed.html', {'form': sub})

Dota2_trader/dota2_deco/templates/dota2_deco/detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'detail_style.css' %}">
</head>
<body>

<form action="#" style="border:1px solid #ccc" method="POST">
<div class="container">
<h1>Decoration describtion:</h1>
<div class="decoration_info">
<ul>
  <li><label>Item:  </label>{{decoration.decoration_name}}</li>
  <li><label>Champion:  </label>{{decoration.decoration_champion}}</li>
  <li><label>Part:  </label>{{decoration.decoration_part}}</li>
  <li><label>Rarelity:  </label>{{decoration.decoration_rarelity}}</li>
  <li><label>Recent average price:</label>{{decoration.decoration_average_price}}</li>

</ul>
</div>
<h1>Item Details</h1>
<div class="item_info">
<ul>
  <li><label>Price:  </label>{{item.price}}</li>
  <li><label>Po by:  </label>{{item.publisher_id}}</li>
  <li><label>Date:  </label>{{item.pub_date}}</li>
</ul>
</div>
</form>

</body>
</html>

Dota2_trader/dota2_deco/templates/dota2_deco/index.html
{% load static %}
<header>
    <div class="top_margin">
        <span>
        </span>
        <div><a href="{% url 'login_app:index' %}"><button class="accessbtn">Login</button></a></div>
        <div><a href="{% url 'login_app:index' %}"><button class="accessbtn">Register</button></a></div>
    </div>

    <link rel="stylesheet" href="{% static 'index_style.css' %}">
    <h1>
        <center>Dota2 Trader</center>
    </h1>
</header>

<body>

    <div>
        <center>
            <form action="/dota2_deco/search/" method="POST">
                {% csrf_token %}
                <input type="text" name="keyword" value="{{keyword}}">
                <button type="submit" class="searchbtn">
                    <center>search</center>
                </button>
            </form>
        </center>
    </div>

    {% if user_search_results %}
    <div id="search_result">
        <h2>From your search:</h2>
        <div class="show_box_container">
            {% for item in user_search_results %}
            <div class="show_box">
                <a href="{% url 'dota2_deco:detail' item_id=item.item_id %}">
                    <ul>
                        <li>{{ item.item_type }}</li>
                        <li>{{ item.price }}</li>
                        <li>{{ item.pub_date }}</li>
                        <li>{{ item.publisher_id }}</li>
                    </ul>
                </a>
            </div>
            {% endfor %}
        </div>

    </div>
    {% endif %}

    <div id="default">
        {% if latest_item_list %}
        <h2>The most recent uploads:</h2>
        <div class="show_box_container">
            {% for item in latest_item_list %}
            <div class="show_box">
                <a href="{% url 'dota2_deco:detail' item_id=item.item_id %}">
                    <ul>
                        <li>{{ item.item_type }}</li>
                        <li>{{ item.price }}</li>
                        <li>{{ item.pub_date }}</li>
                        <li>{{ item.publisher_id }}</li>
                    </ul>
                </a>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>No items are available.</p>
        {% endif %}
    </div>

    <footer>
            <div class="top_margin">
                    <div><a href="{% url 'dota2_deco:publish' %}"><button class="accessbtn">upload yours</button></a></div>
                </div>
    </footer>

Dota2_trader/dota2_deco/templates/dota2_deco/publish.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'publish_css.css' %}">
</head>

<body>

<form action="/dota2_deco/publish/item_upload/" style="border:1px solid #ccc" method="POST">
  <div class="container">
    <h1>Publish</h1>
    <p> </p>
    <hr>

    <label for="type"><b>Type</b></label>
    <input id="type" type="text" placeholder="choose your item" name="type" list="item_type" required>
      <datalist id="item_type">
      {% if type_list %}
      {% for item_type in type_list %}
      <option value="{{ item_type }}">{{ item_type.decoration_name }}</option>
      {% endfor %}
      {% else %}
      <option value="no currect valid option">no currect valid option</option>
      {% endif %}
      </datalist>

    <label for="price"><b>Price</b></label>
    <input id="price" type="float" placeholder="Enter price" name="price" required>

    <label>
      <input type="checkbox" checked="checked" name="contact_agreement" style="margin-bottom:15px">agree to the contact
    </label>
    
    <div class="clearfix">
      <button type="submit" class="accessbtn">publish</button>
    </div>
  </div>
</form>

</body>
</html>

Dota2_trader/dota2_deco/templates/dota2_deco/publish_success.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'publish_css.css' %}">
</head>

<body>

<div style="border:1px solid #ccc">
<div class="container">
    <h1>Published Success</h1>
    <p> </p>
    <hr>

    
    <div class="clearfix">
      <a href="{% url 'dota2_deco:index' %}"><button>back to index</button></a>
    </div>
</div>
</div>
</body>
</html>

Dota2_trader/dota2_deco/templates/dota2_deco/search.html
<header>
    <div class="top_margin">
        <span>
        </span>
        <span>
            <span class="header_right">Login</span>
            <span class="header_right">Register</span>
        </span>
    </div>

    <link rel="stylesheet" href="./static/search_style.css">
    <h1>
        <center>Dota2 Trader</center>
    </h1>
</header>

<body>

    <div>
        <center>
            <input type="text" name="keyword">
            <button type="submit" class="searchbtn">
                <center>search</center>
            </button>
        </center>
    </div>

    {% if cheapest_item_list %}
    <h2>Match your search:</h2>
    <div class="show_box_container">
        {% for item in cheapest_item_list %}
        <div class="show_box">
            <a href="{% url 'dota2_deco:detail' item_id %}">
                <ul>
                    <li>{{ item.item_type }}</li>
                    <li>{{ item.price }}</li>
                    <li>publish on {{ item.pub_date }}</li>
                    <li>by {{ item.publisher_id }}</li>
                </ul>
            </a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No items are available.</p>
    {% endif %}

Dota2_trader/login_app/templates/forget_password/failed.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login_page_style.css' %}">
</head>

<body>

  <div class="container">
    <p>Email {{email}} is not registered</p>
  </div>

</body>
</html>

Dota2_trader/login_app/templates/forget_password/forget_password.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login_page_style.css' %}">
</head>

<body>

<form action="password_reset_request" method="POST" style="border:1px solid #ccc">
  <div class="container">
    <h1>Password reseting</h1>
    <p>Please enter your email/username</p>
    <hr>

    <label for="email"><b>Email/username</b></label>
    <input id="username" type="text" placeholder="Enter Email" name="email" required>
    
    <p>Still dont have an account? <a href="#" style="color:dodgerblue">register here</a>.</p>

    <div class="clearfix">
      <button type="submit" class="signupbtn">Send Email</button>
    </div>
  </div>
</form>

</body>
</html>

Dota2_trader/login_app/templates/forget_password/reset_password.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login_page_style.css' %}">
</head>

<body>

<form action="password_reset" style="border:1px solid #ccc">
  <div class="container">
    <h1>Password reseting</h1>
    <p>Please enter your new password</p>
    <hr>
    <input value="{{email}}" name="email" hidden>

    <label for="email"><b>New password</b></label>
    <input id="password" type="password" placeholder="enter your new password" name="password" required>
    
    <label for="email"><b>Confirm new password</b></label>
    <input id="password_confirm" type="password" placeholder="enter your password again" name="password_confirm" required>
    
    <div class="clearfix">
        <button type="submit" class="signupbtn">reset</button>
    </div>

  </div>
</form>

</body>
</html>

Dota2_trader/login_app/templates/forget_password/reset_successed.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login_page_style.css' %}">
</head>

<body>

  <div class="container">
    <p>Password of account with email {{email}} has been reset</p>
  </div>

</body>
</html>

Dota2_trader/login_app/templates/forget_password/successed.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login_page_style.css' %}">
</head>

<body>

  <div class="container">
    <p>The link of resetting has been sent to {{email}}</p>
  </div>

</body>
</html>

Dota2_trader/login_app/templates/login_fail_no_acc.html
<h1>uncorrect email/username</h1>

Dota2_trader/login_app/templates/login_fail_wrong_passw.html
<h1>uncorrect password</h1>

Dota2_trader/login_app/templates/login_page.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'login_page_style.css' %}">
</head>

<body>

<form action="/action_page.php" style="border:1px solid #ccc">
  <div class="container">
    <h1>Login</h1>
    <p>Please login here with your email/username</p>
    <hr>

    <label for="email"><b>Email/username</b></label>
    <input id="username" type="text" placeholder="Enter Email" name="email" required>

    <label for="psw"><b>Password</b></label>
    <input id="password" type="password" placeholder="Enter Password" name="psw" required>

    <label>
      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
    </label>
    
    <p>Forget password? <a href="{% url 'login_app:forget_password' %}" style="color:dodgerblue">reset password</a>.</p>
    <p>Still dont have an account? <a href="#" style="color:dodgerblue">register here</a>.</p>

    <div class="clearfix">
      <button type="button" class="cancelbtn">Cancel</button>
      <button type="submit" class="signupbtn">login</button>
    </div>
  </div>
</form>

</body>
</html>

Dota2_trader/login_app/templates/login_success.html
<h1>Login successfully</h1>